### PR TITLE
fix(web): don't extract _nativeTag in bottomSheet for web

### LINKED ISSUE #27: TypeError: Cannot read property '_nativeTag' of undefined
I'm using this package on the web and I'm getting the error:

Screenshot 2024-09-09 at 2 56 49 PM

Screenshot 2024-09-09 at 2 57 00 PM

The error is coming from these lines: https://github.com/stanleyugwu/react-native-bottom-sheet/blob/b6b00a3/src/components/bottomSheet/index.tsx#L307-L314

### PR DESCRIPTION
**Pull request by remarkablemark**
Fixes #27

### CODE REVIEW

**Comment by stanleyugwu** [comment]
Hey @remarkablemark thanks for finding time to look into this. Did you test for web after the changes you made? Does it work fine?

**Review by stanleyugwu — APPROVED** [review]

**Comment by remarkablemark** [comment]
Yes I have patched and tested this on production.

**Comment by remarkablemark** [comment]
@stanleyugwu thanks for the merge! Will this be released soon?

**Comment by remarkablemark** [comment]
Awesome, thanks so much!

**Comment by stanleyugwu** [comment]
Hey @remarkablemark I just made a release

**Comment by remarkablemark** [comment]
@stanleyugwu Great to hear!

**Pull request merged**
